spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DBurl}
    password: ${password}
    username: ${username}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    port: 587
    username: ${email}
    password: ${emailPassword}
    default-encoding: UTF-8
    transport:
      protocol: smtp
server:
  port: 7070